### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MegaDrive#2]
Some overlays contain transparent / translucent pixels outside the desired area.

Here the list:

Baby's Day Out (USA) (Proto).png
Barney's Hide & Seek Game (USA).png
Battlemaster (USA).png
Budokan - The Martial Spirit (USA).png
Chiki Chiki Boys (USA, Europe).png
Chuck Rock (USA).png
Cliffhanger (USA).png
Clue (USA).png
Columns (World) (v1.1).png
Daffy Duck in Hollywood (Europe) (En,Fr,De,Es,It).png
Desert Demolition Starring Road Runner and Wile E. Coyote (USA, Europe).png
Dick Vitale's 'Awesome, Baby!' College Hoops (USA).png
Dino Dini's Soccer (Europe).png
ESPN Baseball Tonight (USA).png
ESPN National Hockey Night (USA).png
Ex-Mutants (USA, Europe).png
Exo Squad (USA).png
Flashback - The Quest for Identity (USA).png
Growl (USA).png
Jurassic Park - Rampage Edition (USA, Europe).png
Justice League Task Force (World).png
Lotus II (USA, Europe).png
NBA Live 95 (USA, Europe).png
Ooze, The (Japan, USA).png
Ottifants, The (Europe).png
Rambo III (World) (v1.1).png
Rampart (USA).png
Resq (Europe) (Proto).png
Revenge of Shinobi, The (USA, Europe) (Rev B).png
RoboCop versus The Terminator (USA).png
Rock n' Roll Racing (USA).png
Rocket Knight Adventures (USA).png
Striker (Europe).png
Summer Challenge (USA, Europe) (Unl).png
Theme Park (USA, Europe).png
Warsong (USA).png
Wheel of Fortune (USA).png

Here you can see the specific areas that have pixels outside the desired area.

https://drive.google.com/file/d/1nkxWBqLK8HCpNjKEGqhcLheP_BhDzSWX/view?usp=sharing

**Comment by thebezelproject** [comment]
These have been updated.

**Comment by toniosj** [comment]
This still wrong. Ex-Mutants (USA, Europe).png

![Ex-Mutants (USA, Europe)](https://user-images.githubusercontent.com/20826760/75183000-dc602280-5741-11ea-8e05-2336a4e55df1.png)

**Comment by thebezelproject** [comment]
Updated.
