### ISSUE TITLE
Wrong resolution on James 'Buster' Douglas Knockout Boxing (USA, Europe).png

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MegaDrive#3]
1922x1080, it should be 1920x1080.

Here is fixed.

![James 'Buster' Douglas Knockout Boxing (USA, Europe)](https://user-images.githubusercontent.com/20826760/97776837-f4f3c880-1b6b-11eb-82cb-4736ecdfc5a9.png)

**Comment by thebezelproject** [comment]
Cropped all oversized png files.
