### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-MegaDrive#5]
David Crane's Amazing Tennis
Pink Goes to Hollywood
Raiden Trad
Richard Scarry's Busytown
Team USA Basketball
Tecmo World Cup
Zero Wing

![David Crane's Amazing Tennis (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101483528-8ec34800-3958-11eb-9175-9113bd86baa7.png)
![Pink Goes to Hollywood (USA, Europe)_bezel-16-9(cus) - 2_yellow](https://user-images.githubusercontent.com/20826760/101483532-8f5bde80-3958-11eb-8832-5fc5b3030676.png)
![Raiden Densetsu ~ Raiden Trad (Japan, USA)_bezel-16-9(cus) - 2_yellow](https://user-images.githubusercontent.com/20826760/101483536-8ff47500-3958-11eb-8859-eaeff294ae18.png)
![Richard Scarry's Busytown (USA)_bezel-16-9(cus) - 2_yellow](https://user-images.githubusercontent.com/20826760/101483539-908d0b80-3958-11eb-90b4-121982491da3.png)
![Team USA Basketball (USA, Europe)_bezel-16-9(cus) - 2_yellow](https://user-images.githubusercontent.com/20826760/101483540-908d0b80-3958-11eb-8bbe-575db2504150.png)
![Tecmo World Cup (USA)_bezel-16-9(cus) - 2_yellow](https://user-images.githubusercontent.com/20826760/101483544-91be3880-3958-11eb-84bc-28c6fa6ea122.png)
![Zero Wing (Europe)_bezel-16-9(cus) - 1_yellow](https://user-images.githubusercontent.com/20826760/101483547-9256cf00-3958-11eb-8c5c-971da0eaa5ea.png)

**Comment by thebezelproject** [comment]
Updated.
